# Copyright 2022-TODAY Rapsodoo Iberia S.r.L. (www.rapsodoo.com)
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).

{
    'name': 'Agora connector',
    'version': '15.0.1.0.9',
    'category': 'Extra Tools',
    'summary': """Agora connector: Sales in Odoo""",
    'description': """Agora connector: Sales, Customer, Invoice address, Products in Odoo""",
    'license': 'LGPL-3',
    'author': "Rapsodoo Iberia",
    'website': "https://www.rapsodoo.com/es/",
    'depends': [
        'base',
        'mail',
        'sale',
        'sales_team',
        'sale_management',
        'stock',
        'account',
        'account_accountant',
        'analytic',
        'web_tree_header_buttons_always_visible'
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/agora_connector_views.xml',
        'views/product_template_inherit.xml',
        'views/product_pricelist_inherit.xml',
        'views/sale_order_agora.xml',
        'wizards/order_download_date.xml',
        'views/sale_order_view.xml',
        'views/views_inherits.xml',
        'views/sale_center.xml',
        'views/preparation_type.xml',
        'views/preparation_order.xml',
        'views/agora_tax.xml',
        'views/menus.xml',
        'data/agora_data.xml',
        'data/crons.xml',
    ],
    'post_init_hook': 'create_data',
    'installable': True,
    'auto_install': False,
    'application': True,
}
